import { jsPDF } from "jspdf";

interface Clause {
  title: string;
  text: string;
  risk: "safe" | "caution" | "danger";
  explanation: string;
  suggestedAlternative?: string | null;
}

export interface ScanResult {
  documentType: string;
  summary: string;
  clauses: Clause[];
}

export interface CVAnalysis {
  score: number;
  salary_min: number;
  salary_max: number;
  skills: string[];
  missing_skills: string[];
  experience_years: number;
  experience_level: string;
  education_level?: string | null;
  summary: string;
  improvements: string[];
  trajectory?: string | null;
}

const C = {
  dark: [15, 15, 15] as [number, number, number],
  muted: [110, 110, 120] as [number, number, number],
  light: [248, 248, 252] as [number, number, number],
  border: [220, 220, 230] as [number, number, number],
  accent: [101, 67, 240] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  safe: [34, 197, 94] as [number, number, number],
  caution: [202, 148, 8] as [number, number, number],
  danger: [220, 48, 48] as [number, number, number],
  safeLight: [230, 255, 235] as [number, number, number],
  cautionLight: [255, 250, 220] as [number, number, number],
  dangerLight: [255, 235, 235] as [number, number, number],
  altGreen: [235, 255, 240] as [number, number, number],
};

function riskColor(risk: string): [number, number, number] {
  if (risk === "safe") return C.safe;
  if (risk === "caution") return C.caution;
  return C.danger;
}

function scoreColor(score: number): [number, number, number] {
  if (score >= 70) return C.safe;
  if (score >= 40) return C.caution;
  return C.danger;
}

function addPageHeader(doc: jsPDF, W: number, margin: number) {
  doc.setFillColor(...C.dark);
  doc.rect(0, 0, W, 22, "F");
  doc.setTextColor(...C.white);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("FineClause", margin, 10);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(170, 170, 180);
  doc.text("AI Contract Risk Analysis", margin, 17);
  const dateStr = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
  doc.text(dateStr, W - margin, 17, { align: "right" });
}

function addPageFooter(doc: jsPDF, W: number, margin: number, page: number, total: number) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(...C.muted);
  doc.text(
    "Generated by FineClause AI · Not legal advice · For informational purposes only",
    W / 2, 291, { align: "center" }
  );
  doc.text(`Page ${page} of ${total}`, W - margin, 291, { align: "right" });
}

function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve((reader.result as string).split(",")[1]);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

export async function generateScanPDF(
  fileName: string,
  result: ScanResult,
  riskScore: number | null
): Promise<Blob> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210;
  const margin = 16;
  const cw = W - 2 * margin; // content width

  addPageHeader(doc, W, margin);
  let y = 30;

  // Document name
  doc.setTextColor(...C.dark);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  const nameLines = doc.splitTextToSize(fileName.replace(/\.[^.]+$/, ""), cw - 45);
  doc.text(nameLines, margin, y);
  y += nameLines.length * 6;

  if (result.documentType) {
    doc.setFillColor(...C.accent);
    const badge = result.documentType.toUpperCase();
    const bw = doc.getTextWidth(badge) + 8;
    doc.rect(margin, y, bw, 6.5, "F");
    doc.setTextColor(...C.white);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.text(badge, margin + 4, y + 4.5);
    y += 11;
  }

  // Risk score row
  if (riskScore !== null) {
    const sc = scoreColor(riskScore);
    doc.setFillColor(...C.light);
    doc.setDrawColor(...C.border);
    doc.rect(margin, y, cw, 22, "FD");

    // Score number
    doc.setFont("helvetica", "bold");
    doc.setFontSize(26);
    doc.setTextColor(...sc);
    doc.text(String(riskScore), margin + 8, y + 15);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...C.muted);
    doc.text("/100 Risk Score", margin + 8, y + 20);

    const bx = margin + 38;
    const bw2 = cw - 42;
    const by = y + 9;
    const bh = 4;

    // Stats
    const dC = result.clauses.filter(c => c.risk === "danger").length;
    const caC = result.clauses.filter(c => c.risk === "caution").length;
    const sC = result.clauses.filter(c => c.risk === "safe").length;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...C.danger);
    doc.text(`${dC} High Risk`, bx, by - 2);
    const tw1 = doc.getTextWidth(`${dC} High Risk`);
    doc.setTextColor(...C.caution);
    doc.text(`  ${caC} Caution`, bx + tw1, by - 2);
    const tw2 = doc.getTextWidth(`  ${caC} Caution`);
    doc.setTextColor(...C.safe);
    doc.text(`  ${sC} Safe`, bx + tw1 + tw2, by - 2);

    // Bar background
    doc.setFillColor(210, 210, 220);
    doc.rect(bx, by + 1, bw2, bh, "F");
    doc.setFillColor(...sc);
    doc.rect(bx, by + 1, bw2 * (riskScore / 100), bh, "F");

    y += 27;
  }

  // Summary
  doc.setFillColor(...C.accent);
  doc.rect(margin, y, cw, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...C.white);
  doc.text("  DOCUMENT SUMMARY", margin, y + 4.2);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...C.dark);
  const sumLines = doc.splitTextToSize(result.summary, cw);
  doc.text(sumLines, margin, y);
  y += sumLines.length * 4.8 + 8;

  // Clauses header
  doc.setFillColor(...C.dark);
  doc.rect(margin, y, cw, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...C.white);
  doc.text(`  CLAUSE BREAKDOWN  (${result.clauses.length} clauses)`, margin, y + 4.2);
  y += 9;

  for (let i = 0; i < result.clauses.length; i++) {
    const clause = result.clauses[i];
    const rc = riskColor(clause.risk);

    if (y > 260) {
      doc.addPage();
      addPageHeader(doc, W, margin);
      y = 28;
    }

    const blockY = y;

    // Risk badge
    const badgeLabel = clause.risk === "danger" ? "HIGH RISK" : clause.risk.toUpperCase();
    const badgeW = doc.getTextWidth(badgeLabel) + 8;
    doc.setFillColor(...rc);
    doc.rect(W - margin - badgeW, y - 1, badgeW, 6, "F");
    doc.setTextColor(...C.white);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    doc.text(badgeLabel, W - margin - badgeW + 4, y + 3.5);

    // Clause title
    doc.setTextColor(...C.dark);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(`${i + 1}.  ${clause.title}`, margin + 4, y + 3.5);
    y += 8;

    // Text excerpt
    if (clause.text) {
      const excerpt = clause.text.length > 150 ? clause.text.slice(0, 150) + "…" : clause.text;
      const exLines = doc.splitTextToSize(`"${excerpt}"`, cw - 4);
      const exH = exLines.length * 4 + 4;
      doc.setFillColor(242, 242, 248);
      doc.rect(margin + 4, y, cw - 4, exH, "F");
      doc.setFont("helvetica", "italic");
      doc.setFontSize(7.5);
      doc.setTextColor(80, 80, 100);
      doc.text(exLines, margin + 6, y + 3.5);
      y += exH + 3;
    }

    // Explanation
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...C.dark);
    const expLines = doc.splitTextToSize(clause.explanation, cw - 4);
    doc.text(expLines, margin + 4, y);
    y += expLines.length * 4.5 + 3;

    // Suggested alternative
    if (clause.suggestedAlternative) {
      if (y > 255) { doc.addPage(); addPageHeader(doc, W, margin); y = 28; }
      const altLines = doc.splitTextToSize(clause.suggestedAlternative, cw - 8);
      const altH = altLines.length * 4 + 8;
      doc.setFillColor(...C.altGreen);
      doc.setDrawColor(150, 210, 160);
      doc.rect(margin + 4, y, cw - 4, altH, "FD");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(30, 120, 60);
      doc.text("Suggested Alternative:", margin + 7, y + 4.5);
      doc.setFont("helvetica", "normal");
      doc.text(altLines, margin + 7, y + 9);
      y += altH + 4;
    }

    // Left accent bar
    doc.setFillColor(...rc);
    doc.rect(margin, blockY - 1, 2.5, y - blockY + 3, "F");

    y += 4;
    doc.setDrawColor(...C.border);
    doc.line(margin, y - 2, W - margin, y - 2);
  }

  // Add footers
  const totalPages = (doc.internal as any).getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    addPageFooter(doc, W, margin, p, totalPages);
  }

  return doc.output("blob");
}

export async function generateCVPDF(
  fileName: string,
  analysis: CVAnalysis
): Promise<Blob> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210;
  const margin = 16;
  const cw = W - 2 * margin;

  // Custom header for CV
  doc.setFillColor(...C.dark);
  doc.rect(0, 0, W, 22, "F");
  doc.setTextColor(...C.white);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("FineClause", margin, 10);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(170, 170, 180);
  doc.text("CV Analysis Report", margin, 17);
  const dateStr = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
  doc.text(dateStr, W - margin, 17, { align: "right" });

  let y = 30;

  // CV name
  doc.setTextColor(...C.dark);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  const nameLines = doc.splitTextToSize(fileName.replace(/\.[^.]+$/, ""), cw);
  doc.text(nameLines, margin, y);
  y += nameLines.length * 6 + 2;

  // Score + experience badge row
  const sc = scoreColor(analysis.score);
  const scoreLabel = analysis.score >= 80 ? "EXCELLENT" : analysis.score >= 60 ? "GOOD" : analysis.score >= 40 ? "NEEDS WORK" : "WEAK";

  // Score card
  const cardH = 28;
  doc.setFillColor(...C.light);
  doc.setDrawColor(...C.border);
  doc.rect(margin, y, cw / 3 - 3, cardH, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(...sc);
  doc.text(String(analysis.score), margin + 4, y + 18);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...C.muted);
  doc.text("CV SCORE", margin + 4, y + 24);
  doc.setFillColor(...sc);
  const slW = doc.getTextWidth(scoreLabel) + 6;
  doc.rect(margin + 4, y + 5, slW, 5.5, "F");
  doc.setTextColor(...C.white);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(6.5);
  doc.text(scoreLabel, margin + 7, y + 9);

  // Salary card
  const card2X = margin + cw / 3 + 1;
  const card2W = cw / 3 - 2;
  doc.setFillColor(...C.light);
  doc.setDrawColor(...C.border);
  doc.rect(card2X, y, card2W, cardH, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...C.dark);
  const salStr = `€${Math.round(analysis.salary_min / 1000)}k–€${Math.round(analysis.salary_max / 1000)}k`;
  doc.text(salStr, card2X + 4, y + 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...C.muted);
  doc.text("SALARY RANGE", card2X + 4, y + 20);
  doc.text("Estimated annual", card2X + 4, y + 25);

  // Experience card
  const card3X = margin + (cw / 3) * 2 + 3;
  const card3W = cw - (cw / 3) * 2 - 3;
  doc.setFillColor(...C.light);
  doc.setDrawColor(...C.border);
  doc.rect(card3X, y, card3W, cardH, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...C.dark);
  doc.text(`${analysis.experience_years}yrs`, card3X + 4, y + 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...C.muted);
  doc.text(analysis.experience_level.toUpperCase(), card3X + 4, y + 18);
  if (analysis.education_level) {
    doc.text(analysis.education_level, card3X + 4, y + 23);
  }

  y += cardH + 9;

  // Progress bar
  doc.setFillColor(210, 210, 220);
  doc.rect(margin, y, cw, 4, "F");
  doc.setFillColor(...sc);
  doc.rect(margin, y, cw * (analysis.score / 100), 4, "F");
  y += 9;

  // Summary
  doc.setFillColor(...C.accent);
  doc.rect(margin, y, cw, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...C.white);
  doc.text("  PROFILE SUMMARY", margin, y + 4.2);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...C.dark);
  const sumLines = doc.splitTextToSize(analysis.summary, cw);
  doc.text(sumLines, margin, y);
  y += sumLines.length * 4.8 + 5;

  if (analysis.trajectory) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(...C.muted);
    const tLines = doc.splitTextToSize(`Career Trajectory: ${analysis.trajectory}`, cw - 4);
    doc.text(tLines, margin + 2, y);
    y += tLines.length * 4.5 + 8;
  }

  // Skills side by side
  const halfW = (cw - 4) / 2;

  // Present skills
  doc.setFillColor(34, 160, 70);
  doc.rect(margin, y, halfW, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...C.white);
  doc.text("  YOUR SKILLS", margin, y + 4.2);

  // Missing skills
  doc.setFillColor(...C.caution);
  doc.rect(margin + halfW + 4, y, halfW, 6, "F");
  doc.text("  SKILL GAPS", margin + halfW + 4, y + 4.2);
  y += 8;

  const skillsStartY = y;
  let lY = skillsStartY;
  let rY = skillsStartY;

  // Skills pills (left column)
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  const skillsPerRow = 2;
  const pillW = (halfW - (skillsPerRow - 1) * 3) / skillsPerRow;

  analysis.skills.slice(0, 16).forEach((skill, idx) => {
    const col = idx % skillsPerRow;
    const row = Math.floor(idx / skillsPerRow);
    const px = margin + col * (pillW + 3);
    const py = lY + row * 7;
    doc.setFillColor(220, 240, 225);
    doc.setDrawColor(140, 200, 155);
    doc.rect(px, py, pillW, 5.5, "FD");
    doc.setTextColor(30, 100, 50);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    const skillText = skill.length > 15 ? skill.slice(0, 14) + "…" : skill;
    doc.text(skillText, px + 2, py + 3.8);
  });
  lY += Math.ceil(Math.min(analysis.skills.length, 16) / skillsPerRow) * 7 + 5;

  // Missing skills (right column)
  analysis.missing_skills.slice(0, 16).forEach((skill, idx) => {
    const col = idx % skillsPerRow;
    const row = Math.floor(idx / skillsPerRow);
    const px = margin + halfW + 4 + col * (pillW + 3);
    const py = rY + row * 7;
    doc.setFillColor(255, 245, 210);
    doc.setDrawColor(210, 170, 60);
    doc.rect(px, py, pillW, 5.5, "FD");
    doc.setTextColor(120, 85, 0);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    const skillText = skill.length > 15 ? skill.slice(0, 14) + "…" : skill;
    doc.text(skillText, px + 2, py + 3.8);
  });
  rY += Math.ceil(Math.min(analysis.missing_skills.length, 16) / skillsPerRow) * 7 + 5;

  y = Math.max(lY, rY) + 5;

  // Improvements
  if (y > 230) { doc.addPage(); y = 28; }
  doc.setFillColor(...C.dark);
  doc.rect(margin, y, cw, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...C.white);
  doc.text("  TOP IMPROVEMENTS", margin, y + 4.2);
  y += 9;

  analysis.improvements.forEach((item, i) => {
    if (y > 265) { doc.addPage(); y = 28; }
    const lines = doc.splitTextToSize(item, cw - 14);
    const bh = lines.length * 4.5 + 5;
    doc.setFillColor(...C.light);
    doc.setDrawColor(...C.border);
    doc.rect(margin, y, cw, bh, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...C.accent);
    doc.text(String(i + 1).padStart(2, "0"), margin + 3, y + bh / 2 + 2);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...C.dark);
    doc.text(lines, margin + 12, y + 4.5);
    y += bh + 3;
  });

  // Footer
  const totalPages = (doc.internal as any).getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(...C.muted);
    doc.text(
      "Generated by FineClause AI · Not legal advice · For informational purposes only",
      W / 2, 291, { align: "center" }
    );
    doc.text(`Page ${p} of ${totalPages}`, W - margin, 291, { align: "right" });
  }

  return doc.output("blob");
}

export async function sharePDFReport(
  blob: Blob,
  pdfFileName: string,
  shareTitle: string
): Promise<void> {
  const { Filesystem, Directory } = await import("@capacitor/filesystem");
  const { Share } = await import("@capacitor/share");

  const base64 = await blobToBase64(blob);

  await Filesystem.writeFile({
    path: pdfFileName,
    data: base64,
    directory: Directory.Documents,
  });

  const { uri } = await Filesystem.getUri({
    path: pdfFileName,
    directory: Directory.Documents,
  });

  await Share.share({
    title: shareTitle,
    url: uri,
    dialogTitle: `Share ${shareTitle}`,
  });
}
